/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gnenc.internet.mycourses.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.gnenc.internet.mycourses.model.Course;
import org.gnenc.internet.mycourses.service.CourseLocalService;
import org.gnenc.internet.mycourses.service.HostLocalService;
import org.gnenc.internet.mycourses.service.SiteLocalService;
import org.gnenc.internet.mycourses.service.UserEnrollmentLocalService;
import org.gnenc.internet.mycourses.service.persistence.CoursePersistence;
import org.gnenc.internet.mycourses.service.persistence.HostPersistence;
import org.gnenc.internet.mycourses.service.persistence.SitePersistence;
import org.gnenc.internet.mycourses.service.persistence.UserEnrollmentPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the course local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.gnenc.internet.mycourses.service.impl.CourseLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link org.gnenc.internet.mycourses.service.CourseLocalServiceUtil} to access the course local service.
 * </p>
 *
 * @author Drew Blessing/Stephen Hunter
 * @see org.gnenc.internet.mycourses.service.impl.CourseLocalServiceImpl
 * @see org.gnenc.internet.mycourses.service.CourseLocalServiceUtil
 * @generated
 */
public abstract class CourseLocalServiceBaseImpl implements CourseLocalService {
	/**
	 * Adds the course to the database. Also notifies the appropriate model listeners.
	 *
	 * @param course the course to add
	 * @return the course that was added
	 * @throws SystemException if a system exception occurred
	 */
	public Course addCourse(Course course) throws SystemException {
		course.setNew(true);

		return coursePersistence.update(course, false);
	}

	/**
	 * Creates a new course with the primary key. Does not add the course to the database.
	 *
	 * @param id the primary key for the new course
	 * @return the new course
	 */
	public Course createCourse(long id) {
		return coursePersistence.create(id);
	}

	/**
	 * Deletes the course with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the course to delete
	 * @throws PortalException if a course with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteCourse(long id) throws PortalException, SystemException {
		coursePersistence.remove(id);
	}

	/**
	 * Deletes the course from the database. Also notifies the appropriate model listeners.
	 *
	 * @param course the course to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteCourse(Course course) throws SystemException {
		coursePersistence.remove(course);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return coursePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return coursePersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return coursePersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return coursePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the course with the primary key.
	 *
	 * @param id the primary key of the course to get
	 * @return the course
	 * @throws PortalException if a course with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Course getCourse(long id) throws PortalException, SystemException {
		return coursePersistence.findByPrimaryKey(id);
	}

	/**
	 * Gets a range of all the courses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of courses to return
	 * @param end the upper bound of the range of courses to return (not inclusive)
	 * @return the range of courses
	 * @throws SystemException if a system exception occurred
	 */
	public List<Course> getCourses(int start, int end)
		throws SystemException {
		return coursePersistence.findAll(start, end);
	}

	/**
	 * Gets the number of courses.
	 *
	 * @return the number of courses
	 * @throws SystemException if a system exception occurred
	 */
	public int getCoursesCount() throws SystemException {
		return coursePersistence.countAll();
	}

	/**
	 * Updates the course in the database. Also notifies the appropriate model listeners.
	 *
	 * @param course the course to update
	 * @return the course that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Course updateCourse(Course course) throws SystemException {
		course.setNew(false);

		return coursePersistence.update(course, true);
	}

	/**
	 * Updates the course in the database. Also notifies the appropriate model listeners.
	 *
	 * @param course the course to update
	 * @param merge whether to merge the course with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the course that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Course updateCourse(Course course, boolean merge)
		throws SystemException {
		course.setNew(false);

		return coursePersistence.update(course, merge);
	}

	/**
	 * Gets the course local service.
	 *
	 * @return the course local service
	 */
	public CourseLocalService getCourseLocalService() {
		return courseLocalService;
	}

	/**
	 * Sets the course local service.
	 *
	 * @param courseLocalService the course local service
	 */
	public void setCourseLocalService(CourseLocalService courseLocalService) {
		this.courseLocalService = courseLocalService;
	}

	/**
	 * Gets the course persistence.
	 *
	 * @return the course persistence
	 */
	public CoursePersistence getCoursePersistence() {
		return coursePersistence;
	}

	/**
	 * Sets the course persistence.
	 *
	 * @param coursePersistence the course persistence
	 */
	public void setCoursePersistence(CoursePersistence coursePersistence) {
		this.coursePersistence = coursePersistence;
	}

	/**
	 * Gets the site local service.
	 *
	 * @return the site local service
	 */
	public SiteLocalService getSiteLocalService() {
		return siteLocalService;
	}

	/**
	 * Sets the site local service.
	 *
	 * @param siteLocalService the site local service
	 */
	public void setSiteLocalService(SiteLocalService siteLocalService) {
		this.siteLocalService = siteLocalService;
	}

	/**
	 * Gets the site persistence.
	 *
	 * @return the site persistence
	 */
	public SitePersistence getSitePersistence() {
		return sitePersistence;
	}

	/**
	 * Sets the site persistence.
	 *
	 * @param sitePersistence the site persistence
	 */
	public void setSitePersistence(SitePersistence sitePersistence) {
		this.sitePersistence = sitePersistence;
	}

	/**
	 * Gets the user enrollment local service.
	 *
	 * @return the user enrollment local service
	 */
	public UserEnrollmentLocalService getUserEnrollmentLocalService() {
		return userEnrollmentLocalService;
	}

	/**
	 * Sets the user enrollment local service.
	 *
	 * @param userEnrollmentLocalService the user enrollment local service
	 */
	public void setUserEnrollmentLocalService(
		UserEnrollmentLocalService userEnrollmentLocalService) {
		this.userEnrollmentLocalService = userEnrollmentLocalService;
	}

	/**
	 * Gets the user enrollment persistence.
	 *
	 * @return the user enrollment persistence
	 */
	public UserEnrollmentPersistence getUserEnrollmentPersistence() {
		return userEnrollmentPersistence;
	}

	/**
	 * Sets the user enrollment persistence.
	 *
	 * @param userEnrollmentPersistence the user enrollment persistence
	 */
	public void setUserEnrollmentPersistence(
		UserEnrollmentPersistence userEnrollmentPersistence) {
		this.userEnrollmentPersistence = userEnrollmentPersistence;
	}

	/**
	 * Gets the host local service.
	 *
	 * @return the host local service
	 */
	public HostLocalService getHostLocalService() {
		return hostLocalService;
	}

	/**
	 * Sets the host local service.
	 *
	 * @param hostLocalService the host local service
	 */
	public void setHostLocalService(HostLocalService hostLocalService) {
		this.hostLocalService = hostLocalService;
	}

	/**
	 * Gets the host persistence.
	 *
	 * @return the host persistence
	 */
	public HostPersistence getHostPersistence() {
		return hostPersistence;
	}

	/**
	 * Sets the host persistence.
	 *
	 * @param hostPersistence the host persistence
	 */
	public void setHostPersistence(HostPersistence hostPersistence) {
		this.hostPersistence = hostPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = coursePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = CourseLocalService.class)
	protected CourseLocalService courseLocalService;
	@BeanReference(type = CoursePersistence.class)
	protected CoursePersistence coursePersistence;
	@BeanReference(type = SiteLocalService.class)
	protected SiteLocalService siteLocalService;
	@BeanReference(type = SitePersistence.class)
	protected SitePersistence sitePersistence;
	@BeanReference(type = UserEnrollmentLocalService.class)
	protected UserEnrollmentLocalService userEnrollmentLocalService;
	@BeanReference(type = UserEnrollmentPersistence.class)
	protected UserEnrollmentPersistence userEnrollmentPersistence;
	@BeanReference(type = HostLocalService.class)
	protected HostLocalService hostLocalService;
	@BeanReference(type = HostPersistence.class)
	protected HostPersistence hostPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}