/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gnenc.internet.mycourses.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Site service. Represents a row in the &quot;MC_Site&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gnenc.internet.mycourses.model.impl.SiteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gnenc.internet.mycourses.model.impl.SiteImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a site model instance should use the {@link Site} interface instead.
 * </p>
 *
 * @author Drew Blessing/Stephen Hunter
 * @see Site
 * @see org.gnenc.internet.mycourses.model.impl.SiteImpl
 * @see org.gnenc.internet.mycourses.model.impl.SiteModelImpl
 * @generated
 */
public interface SiteModel extends BaseModel<Site> {
	/**
	 * Gets the primary key of this site.
	 *
	 * @return the primary key of this site
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this site
	 *
	 * @param pk the primary key of this site
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the site id of this site.
	 *
	 * @return the site id of this site
	 */
	public long getSiteId();

	/**
	 * Sets the site id of this site.
	 *
	 * @param siteId the site id of this site
	 */
	public void setSiteId(long siteId);

	/**
	 * Gets the site name of this site.
	 *
	 * @return the site name of this site
	 */
	@AutoEscape
	public String getSiteName();

	/**
	 * Sets the site name of this site.
	 *
	 * @param siteName the site name of this site
	 */
	public void setSiteName(String siteName);

	/**
	 * Gets the url of this site.
	 *
	 * @return the url of this site
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this site.
	 *
	 * @param url the url of this site
	 */
	public void setUrl(String url);

	/**
	 * Gets the email domain of this site.
	 *
	 * @return the email domain of this site
	 */
	@AutoEscape
	public String getEmailDomain();

	/**
	 * Sets the email domain of this site.
	 *
	 * @param emailDomain the email domain of this site
	 */
	public void setEmailDomain(String emailDomain);

	/**
	 * Gets the db server of this site.
	 *
	 * @return the db server of this site
	 */
	@AutoEscape
	public String getDbServer();

	/**
	 * Sets the db server of this site.
	 *
	 * @param dbServer the db server of this site
	 */
	public void setDbServer(String dbServer);

	/**
	 * Gets the db name of this site.
	 *
	 * @return the db name of this site
	 */
	@AutoEscape
	public String getDbName();

	/**
	 * Sets the db name of this site.
	 *
	 * @param dbName the db name of this site
	 */
	public void setDbName(String dbName);

	/**
	 * Gets the db user of this site.
	 *
	 * @return the db user of this site
	 */
	@AutoEscape
	public String getDbUser();

	/**
	 * Sets the db user of this site.
	 *
	 * @param dbUser the db user of this site
	 */
	public void setDbUser(String dbUser);

	/**
	 * Gets the db pass of this site.
	 *
	 * @return the db pass of this site
	 */
	@AutoEscape
	public String getDbPass();

	/**
	 * Sets the db pass of this site.
	 *
	 * @param dbPass the db pass of this site
	 */
	public void setDbPass(String dbPass);

	/**
	 * Gets the company id of this site.
	 *
	 * @return the company id of this site
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this site.
	 *
	 * @param companyId the company id of this site
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets a copy of this site as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Site toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Site site);

	public int hashCode();

	public String toString();

	public String toXmlString();
}